#done by Logan Mifflin
#This script is for sbatch jobs on hpc3
#This runs fit_probe to train a whitebox probe

# Contents:
#config vars set fit options
#env setup loads python and venv
#run block starts fit_probe.py

#SBATCH --job-name=tabletalk_fit_probe
#SBATCH --account=cs175a_class_gpu
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=4:00:00
#SBATCH --output=outputs/fit_probe_%j.log
#SBATCH --error=outputs/fit_probe_%j.err

#config vars
TRAINING_DATA=${TRAINING_DATA:-}
OUTPUT=${OUTPUT:-}
EPOCHS=${EPOCHS:-30}
LR=${LR:-0.001}
BATCH_SIZE=${BATCH_SIZE:-64}
VAL_SPLIT=${VAL_SPLIT:-0.2}
SEED=${SEED:-42}

#strict shell mode
set -euo pipefail

#go to repo
REPO_DIR="$HOME/TableTalk"
cd "$REPO_DIR"

#load python env
module load python/3.10.2
source .venv/bin/activate

#pick latest training file if missing
if [ -z "$TRAINING_DATA" ]; then
    LATEST_PT=$(ls -t outputs/whitebox_data_*.pt 2>/dev/null | head -n 1 || true)
    if [ -z "$LATEST_PT" ]; then
        echo "ERROR: TRAINING_DATA not set and no whitebox_data_*.pt found in outputs/."
        echo "Pass it via: sbatch --export=ALL,TRAINING_DATA=path/to/data.pt slurm/run_fit_probe.sh"
        exit 1
    fi
    TRAINING_DATA="$LATEST_PT"
    echo "Auto-selected latest training data: $TRAINING_DATA"
fi

#set pytorch alloc behavior
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

#make output dir
mkdir -p outputs

#job header
echo "TableTalk — Fit Whitebox Probe"
echo "training_data: ${TRAINING_DATA}"
echo "output: ${OUTPUT:-<auto-generated>}"
echo "epochs: ${EPOCHS} lr: ${LR}"
echo "batch_size: ${BATCH_SIZE} val_split: ${VAL_SPLIT}"
echo "seed: ${SEED}"
echo "job id: ${SLURM_JOB_ID}"
echo "node: $(hostname)"

#optional output arg
OUTPUT_ARG=()
[ -n "$OUTPUT" ] && OUTPUT_ARG=(--output "$OUTPUT")

#run fit probe
python scripts/fit_probe.py \
    --training_data "${TRAINING_DATA}" \
    --epochs "${EPOCHS}" \
    --lr "${LR}" \
    --batch_size "${BATCH_SIZE}" \
    --val_split "${VAL_SPLIT}" \
    --seed "${SEED}" \
    "${OUTPUT_ARG[@]}"

echo "Done!! outputs written to outputs/ folder"
